In [1]:
#EXP NO.2

In [3]:
#AIM:TO PERFORM SAMPLING AND POPULATION

In [4]:
#NAME:Komal Sawarkar
#ROLL NO.:54
#SUBJECT:DSS
#DATE:6 AUG 2026

In [5]:
#IMPORTING THE BASIC LIBRARY 
import pandas as pd

In [6]:
import os

In [7]:
os.getcwd()

'C:\\Users\\VICTUS'

In [8]:
os.chdir('C:\\Users\\VICTUS\\Downloads')

In [9]:
data=pd.read_csv("heart (1).csv")

In [10]:
data.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [11]:
data.tail()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [12]:
age_above_60=[data["age"]>60]
print(age_above_60)

[0       True
1      False
2      False
3      False
4      False
       ...
298    False
299    False
300     True
301    False
302    False
Name: age, Length: 303, dtype: bool]

In [16]:
print("number of patient with age >60:",len(age_above_60))

number of patient with age >60: 1

data.isna()

In [17]:
data.isna().any()

age         False
sex         False
cp          False
trestbps    False
chol        False
fbs         False
restecg     False
thalach     False
exang       False
oldpeak     False
slope       False
ca          False
thal        False
target      False
dtype: bool

In [18]:
data.isna().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64