# 1. DATA AQUISITION

In [1]:
#Exp No.: 1

In [2]:
#Aim: To perform operation of Data Aquisition

In [3]:
# Name:Komal Sawarkar
# Roll no.:54
# Sec:C
# Subject:DSS
# Date:29/07/26

In [4]:
#importing the basic library
import pandas as pd

In [5]:
import os

In [6]:
os.getcwd()

'C:\\Users\\VICTUS'

In [7]:
os.chdir('C:\\Users\\VICTUS\\Downloads')

In [8]:
data=pd.read_csv("heart.csv")

In [9]:
data.head()

   age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak
0  NaN  NaN NaN       NaN   NaN  NaN      NaN      NaN    NaN      NaN
1  NaN  NaN NaN       NaN   NaN  NaN      NaN      NaN    NaN      NaN
2  NaN  NaN NaN       NaN   NaN  NaN      NaN      NaN    NaN      NaN
3  NaN  NaN NaN       NaN   NaN  NaN      NaN      NaN    NaN      NaN
4  NaN  NaN NaN       NaN   NaN  NaN      NaN      NaN    NaN      NaN

In [10]:
data.tail()

     age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak
119  NaN  NaN NaN       NaN   NaN  NaN      NaN      NaN    NaN      NaN
120  NaN  NaN NaN       NaN   NaN  NaN      NaN      NaN    NaN      NaN
121  NaN  NaN NaN       NaN   NaN  NaN      NaN      NaN    NaN      NaN
122  NaN  NaN NaN       NaN   NaN  NaN      NaN      NaN    NaN      NaN
123  NaN  NaN NaN       NaN   NaN  NaN      NaN      NaN    NaN      NaN

In [11]:
data.describe()

       age  sex   cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak
count  0.0  0.0  0.0       0.0   0.0  0.0      0.0      0.0    0.0      0.0
mean   NaN  NaN  NaN       NaN   NaN  NaN      NaN      NaN    NaN      NaN
std    NaN  NaN  NaN       NaN   NaN  NaN      NaN      NaN    NaN      NaN
min    NaN  NaN  NaN       NaN   NaN  NaN      NaN      NaN    NaN      NaN
25%    NaN  NaN  NaN       NaN   NaN  NaN      NaN      NaN    NaN      NaN
50%    NaN  NaN  NaN       NaN   NaN  NaN      NaN      NaN    NaN      NaN
75%    NaN  NaN  NaN       NaN   NaN  NaN      NaN      NaN    NaN      NaN
max    NaN  NaN  NaN       NaN   NaN  NaN      NaN      NaN    NaN      NaN